<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUIZC1Ph\AcmeKernel72088::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUIZC1Ph/AcmeKernel72088.php') {
    touch(__DIR__.'/ContainerUIZC1Ph.legacy');

    return;
}

if (!\class_exists(AcmeKernel72088::class, false)) {
    \class_alias(\ContainerUIZC1Ph\AcmeKernel72088::class, AcmeKernel72088::class, false);
}

return new \ContainerUIZC1Ph\AcmeKernel72088([
    'container.build_hash' => 'UIZC1Ph',
    'container.build_id' => '8e9bb74e',
    'container.build_time' => 1738267904,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUIZC1Ph');
