<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD5iFlCZ\AcmeKernel59411::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD5iFlCZ/AcmeKernel59411.php') {
    touch(__DIR__.'/ContainerD5iFlCZ.legacy');

    return;
}

if (!\class_exists(AcmeKernel59411::class, false)) {
    \class_alias(\ContainerD5iFlCZ\AcmeKernel59411::class, AcmeKernel59411::class, false);
}

return new \ContainerD5iFlCZ\AcmeKernel59411([
    'container.build_hash' => 'D5iFlCZ',
    'container.build_id' => '30afe679',
    'container.build_time' => 1738267792,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD5iFlCZ');
