<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPZ7ds32\AcmeKernel79090::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPZ7ds32/AcmeKernel79090.php') {
    touch(__DIR__.'/ContainerPZ7ds32.legacy');

    return;
}

if (!\class_exists(AcmeKernel79090::class, false)) {
    \class_alias(\ContainerPZ7ds32\AcmeKernel79090::class, AcmeKernel79090::class, false);
}

return new \ContainerPZ7ds32\AcmeKernel79090([
    'container.build_hash' => 'PZ7ds32',
    'container.build_id' => '6e1798ff',
    'container.build_time' => 1738268085,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPZ7ds32');
