<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNzX7lkR\AcmeKernel23523::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNzX7lkR/AcmeKernel23523.php') {
    touch(__DIR__.'/ContainerNzX7lkR.legacy');

    return;
}

if (!\class_exists(AcmeKernel23523::class, false)) {
    \class_alias(\ContainerNzX7lkR\AcmeKernel23523::class, AcmeKernel23523::class, false);
}

return new \ContainerNzX7lkR\AcmeKernel23523([
    'container.build_hash' => 'NzX7lkR',
    'container.build_id' => '3d3a4609',
    'container.build_time' => 1738267537,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNzX7lkR');
