<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMEsxKd\AcmeKernel32032::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMEsxKd/AcmeKernel32032.php') {
    touch(__DIR__.'/ContainerNMEsxKd.legacy');

    return;
}

if (!\class_exists(AcmeKernel32032::class, false)) {
    \class_alias(\ContainerNMEsxKd\AcmeKernel32032::class, AcmeKernel32032::class, false);
}

return new \ContainerNMEsxKd\AcmeKernel32032([
    'container.build_hash' => 'NMEsxKd',
    'container.build_id' => 'e2ac683e',
    'container.build_time' => 1738267981,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMEsxKd');
