<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnfXk2r\KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnfXk2r/KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVnfXk2r.legacy');

    return;
}

if (!\class_exists(KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVnfXk2r\KernelDevDebugContainer::class, KernelDevDebugContainer::class, false);
}

return new \ContainerVnfXk2r\KernelDevDebugContainer([
    'container.build_hash' => 'VnfXk2r',
    'container.build_id' => '87727316',
    'container.build_time' => 1738268663,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnfXk2r');
