<?php

namespace ContainerZI7rQ7L;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageDispatcherServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\MessageDispatcherService' shared autowired service.
     *
     * @return \App\MessageDispatcher\Infrastructure\Services\MessageDispatcherService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MessageDispatcherService.php';

        return $container->services['App\\MessageDispatcher\\Infrastructure\\Services\\MessageDispatcherService'] = new \App\MessageDispatcher\Infrastructure\Services\MessageDispatcherService(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
