<?php

namespace ContainerTttukho;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpServerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\HTTPServer\Infrastructure\Service\HttpServerService' shared autowired service.
     *
     * @return \App\HTTPServer\Infrastructure\Service\HttpServerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/HTTPServer/Infrastructure/Service/HttpServerService.php';

        return $container->services['App\\HTTPServer\\Infrastructure\\Service\\HttpServerService'] = new \App\HTTPServer\Infrastructure\Service\HttpServerService('0.0.0.0', 9503, $container);
    }
}
