<?php

namespace ContainerTttukho;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageDispatcherService2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\MessageDispatcherService' shared autowired service.
     *
     * @return \App\Service\MessageDispatcherService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Service\\MessageDispatcherService'] = new \App\Service\MessageDispatcherService();
    }
}
